# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000, null=True)),
                ('pub_date', models.DateField(null=True)),
                ('other_stuff', models.IntegerField(null=True, verbose_name='Other Stuff')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('creationDT', models.DateTimeField(null=True)),
                ('modificationDT', models.DateTimeField(null=True)),
            ],
        ),
    ]
