# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxNumReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_receipt', models.IntegerField(blank=True, null=True)),
                ('gen_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(max_length=511, upload_to='uploads/%Y/%m/%d')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('creation_DT', models.DateTimeField()),
                ('modification_DT', models.DateTimeField()),
                ('user', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
