# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='comment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
