# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170410_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(max_length=510, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
