# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160516_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
