# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160516_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
