# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20170410_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='file',
        ),
        migrations.AddField(
            model_name='receipt',
            name='file_url',
            field=models.CharField(default='blahblah', max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='filename',
            field=models.CharField(default='blah', max_length=999),
            preserve_default=False,
        ),
    ]
