# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170411_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='filename',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
