# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_password_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
