# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_auto_20170412_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('doctor_name', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('left_eye_sphere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_eye_cylinder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_eye_axis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_eye_prism', models.DecimalField(decimal_places=2, max_digits=10)),
                ('left_eye_base', models.CharField(max_length=255)),
                ('left_eye_added_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('right_eye_sphere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('right_eye_cylinder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('right_eye_axis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('right_eye_prism', models.DecimalField(decimal_places=2, max_digits=10)),
                ('right_eye_base', models.CharField(max_length=255)),
                ('right_eye_added_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filename', models.CharField(blank=True, max_length=999)),
                ('file_url', models.CharField(blank=True, max_length=999)),
                ('comment', models.CharField(blank=True, max_length=254)),
                ('creation_DT', models.DateTimeField()),
                ('modification_DT', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
