# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160518_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='isPublic',
        ),
        migrations.RemoveField(
            model_name='passwordaccesspoint',
            name='relationshipDT',
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='modificationDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordaccesspoint',
            name='DT_established',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='creationDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='modificationDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
