# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160715_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='creationDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
