# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone




class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20160803_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
