# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 01:08
from __future__ import unicode_literals

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20160907_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
