# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20160927_1920'),
    ]



    operations = [
        migrations.AddField(
            model_name='password',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='password',
            name='security_questions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
