# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20161006_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxNumAccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_ap', models.IntegerField(blank=True, null=True)),
                ('gen_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxNumPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num_pwd', models.IntegerField(blank=True, null=True)),
                ('gen_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
