# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_maxnumaccesspoint_maxnumpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='security_questions',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
