# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 11:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0016_passwordtrustedpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('creation_DT', models.DateTimeField(blank=True, null=True)),
                ('modification_DT', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='MaxNumAccessPoint',
            new_name='MaxNumReceipt',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='user',
        ),
        migrations.DeleteModel(
            name='MaxNumPassword',
        ),
        migrations.RemoveField(
            model_name='password',
            name='access_points',
        ),
        migrations.RemoveField(
            model_name='password',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordaccesspoint',
            name='access_point',
        ),
        migrations.RemoveField(
            model_name='passwordaccesspoint',
            name='password',
        ),
        migrations.RemoveField(
            model_name='passwordtrustedpartner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='passwordtrustedpartner',
            name='trusted_partner',
        ),
        migrations.RenameField(
            model_name='maxnumreceipt',
            old_name='max_num_ap',
            new_name='max_num_receipt',
        ),
        migrations.DeleteModel(
            name='AccessPoint',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.DeleteModel(
            name='PasswordAccessPoint',
        ),
        migrations.DeleteModel(
            name='PasswordTrustedPartner',
        ),
    ]
