# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20170329_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
