# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_receipt_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='photo',
        ),
        migrations.AddField(
            model_name='receipt',
            name='docfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
