# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):



    dependencies = [
        ('app1', '0019_auto_20170403_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='creation_DT',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='modification_DT',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store_name',
            field=models.CharField(max_length=255),
        ),
    ]
